name: Notify Main Repo

on:
  push:
    branches: [ main ]

jobs:
  ping-main:
    runs-on: ubuntu-latest
    steps:
      - name: Send signal to Main Repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/your-username/main-repo/dispatches \
          -d '{"event_type": "trigger-build"}'
